export const ActionTypes = {
  SET_INSTRUCTOR: "SET_INSTRUCTOR",
  SET_PLANS: "SET_PLANS",
  SET_VIDEOS: "SET_VIDEOS",

  SELECTED_PLANS: "SELECTED_PLANS",
  SELECTED_INSTRUCTOR: "SELECTED_INSTRUCTOR",
  SELECTED_VIDEOS: "SELECTED_VIDEOS",

  REMOVE_PLANS: "REMOVE_PLANS",
  REMOVE_VIDEOS: "REMOVE_VIDEOS",
};
